# Generated by Django 4.1.3 on 2022-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_constraction_detay_constraction_maliyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Proje resmi'),
        ),
    ]
